# Generated by Django 3.1.5 on 2021-01-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('URL', models.URLField()),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
