# Generated by Django 3.1.5 on 2021-01-27 16:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('blogs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='URL',
        ),
        migrations.AddField(
            model_name='blog',
            name='path',
            field=models.CharField(default='', max_length=50),
        ),
    ]
