# Generated by Django 3.1.5 on 2021-02-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210127_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='path',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
