# Generated by Django 3.1.5 on 2021-02-04 19:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("slug", models.SlugField(default="")),
                ("title", models.TextField()),
                ("date", models.DateField()),
                ("content", models.TextField()),
            ],
            managers=[
                ("blogs", django.db.models.manager.Manager()),
            ],
        ),
    ]
