# Generated by Django 3.1.5 on 2021-02-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20210212_1608"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myblog",
            managers=[],
        ),
    ]
