# Generated by Django 3.1.5 on 2021-02-12 16:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210212_1622'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myblog',
            managers=[
                ('myblogs', django.db.models.manager.Manager()),
            ],
        ),
    ]
