# Generated by Django 3.1.5 on 2021-02-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20210212_1624"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myblog",
            managers=[],
        ),
    ]
